### ISSUE TITLE
stacktraces

### ISSUE THREAD

**Issue by tomByrer** [zankhq/epicstudio#1]
```bash

9:56:26 PM [vite] Error when evaluating SSR module astro:scripts/page-ssr.js: failed to import "i18next"
|- Error: Cannot find module 'i18next' imported from 'astro:scripts/page-ssr.js'
    at nodeImport (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:56010:25)
    at ssrImport (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:30)
    at eval (astro:scripts/page-ssr.js:4:37)
    at async instantiateModule (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)    

9:56:26 PM [vite] Error when evaluating SSR module D:/doc/prog/astro/epicstudio/src/pages/index.astro: failed to import "astro:scripts/page-ssr.js"
|- Error: Cannot find module 'i18next' imported from 'astro:scripts/page-ssr.js'
    at nodeImport (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:56010:25)
    at ssrImport (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:30)
    at eval (astro:scripts/page-ssr.js:4:37)
    at async instantiateModule (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)    

 error   Cannot find module 'i18next' imported from 'astro:scripts/page-ssr.js'
  File:
    D:\doc\prog\astro\epicstudio\node_modules\.pnpm\vite@4.4.9\node_modules\vite\dist\node\chunks\dep-df561101.js:56010:25
  Code:
    56009 |         if (!resolved) {
    > 56010 |             const err = new Error(`Cannot find module '${id}' imported from '${importer}'`);
            |                         ^
      56011 |             err.code = 'ERR_MODULE_NOT_FOUND';
      56012 |             throw err;
      56013 |         }
  Stacktrace:
Error: Cannot find module 'i18next' imported from 'astro:scripts/page-ssr.js'
    at nodeImport (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:56010:25)
    at ssrImport (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:30)
    at eval (astro:scripts/page-ssr.js:4:37)
    at async instantiateModule (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)    

09:56:26 PM [serve]    404                    /.well-known/gpc.json
9:56:53 PM [vite] Error when evaluating SSR module D:/doc/prog/astro/epicstudio/src/pages/404.astro: failed to import "astro:scripts/page-ssr.js"
|- Error: Cannot find module 'i18next' imported from 'astro:scripts/page-ssr.js'
    at nodeImport (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:56010:25)
    at ssrImport (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:30)
    at eval (astro:scripts/page-ssr.js:4:37)
    at async instantiateModule (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)    

 error   Cannot find module 'i18next' imported from 'astro:scripts/page-ssr.js'
  File:
    D:\doc\prog\astro\epicstudio\node_modules\.pnpm\vite@4.4.9\node_modules\vite\dist\node\chunks\dep-df561101.js:56010:25
  Code:
    56009 |         if (!resolved) {
    > 56010 |             const err = new Error(`Cannot find module '${id}' imported from '${importer}'`);
            |                         ^
      56011 |             err.code = 'ERR_MODULE_NOT_FOUND';
      56012 |             throw err;
      56013 |         }
  Stacktrace:
Error: Cannot find module 'i18next' imported from 'astro:scripts/page-ssr.js'
    at nodeImport (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:56010:25)
    at ssrImport (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:30)
    at eval (astro:scripts/page-ssr.js:4:37)
    at async instantiateModule (file:///D:/doc/prog/astro/epicstudio/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)    ```
I just `pnpm i` then ran the dev script.

You demo looks nice though

**Comment by zanhk** [comment]
Hi @tomByrer, have you tested with npm as well? I ll be able to check this late tomorrow.

Thanks for the feedback

**Comment by zanhk** [comment]
@tomByrer Should be fixed now, take a try and let me know

**Comment by tomByrer** [comment]
WORKS!
cheers
